version: '3'

services:
  mongo:
    networks:
      - family-tree-network
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  family-tree-dev:
    networks:
      - family-tree-network
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - 'mongo'
    container_name: family-tree-dev
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./server/src:/usr/src/app/src
    command: pm2-runtime start ./src/app.js --watch

networks:
  family-tree-network: